# Windsurf Rules File for Photo Description Generator
description:
  - "Photo Description Generator"
  - "This script reads photos from an input folder, uses OpenRouter to classify them, and saves the tags and descriptions to JSON metadata files."
  - "Using php king23/di for dependency injection."

# Default ignores
ignore:
  - ".git"
  - "vendor"
  - "node_modules"
  - "input_photos"
  - "output"
  - ".env"

# Important protection rules
rules:
  - never_modify:
      - ".env"      # Never modify existing .env files

# Build configuration
build:
  - command: "composer install"
    working_directory: "."

# Run configuration
run:
  - command: "php examples/process_photos.php"
    working_directory: "."

# Environmental variables (add your OpenRouter API key here)
env:
  OPENROUTER_API_KEY: "${OPENROUTER_API_KEY}"
  INPUT_FOLDER: "input_photos"
  OUTPUT_FOLDER: "output"
  LOG_LEVEL: "info"

# Pre-tag validation
pre_tag_validation:
  - name: "Run unit tests"
    command: "./vendor/bin/phpunit"
    working_directory: "."
    fail_on_error: true
    description: "All unit tests must pass before tagging a new version"
  
  - name: "Check for skipped tests"
    command: "./vendor/bin/phpunit --list-tests-xml=test-results.xml && grep -q 'status=\"skipped\"' test-results.xml && echo 'ERROR: Skipped tests detected!' && exit 1 || (rm test-results.xml && exit 0)"
    working_directory: "."
    fail_on_error: true
    description: "No tests should be skipped when tagging a new version"

  - name: "Ensure CHANGELOG is updated"
    command: "grep -q $(git describe --tags --abbrev=0) CHANGELOG.md || (echo 'ERROR: Latest version not found in CHANGELOG.md!' && exit 1)"
    working_directory: "."
    fail_on_error: true
    description: "Ensure the CHANGELOG.md file is updated with the latest version"

  - name: "Ensure README up-to-date with latest version"
    command: "grep -q $(git describe --tags --abbrev=0) README.md || (echo 'README WARNING: Please update README.md with latest version and features!' && exit 1)"
    working_directory: "."
    fail_on_error: true
    description: "Prompts to update README with latest version - actual content review is manual"
